# Generated by Django 4.2.4 on 2023-09-07 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0003_alter_advertisement_status_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='advertisements',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='advertisements.advertisement'),
        ),
    ]
