# Generated by Django 4.2.4 on 2023-08-14 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Раздел')),
                ('article', models.ManyToManyField(through='articles.Relationship', to='articles.article')),
            ],
        ),
        migrations.AddField(
            model_name='relationship',
            name='Section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.section'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article'),
        ),
    ]
